# Generated by Django 4.2.6 on 2023-10-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('message_body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.ManyToManyField(to='main.client', verbose_name='Клиенты')),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.emailmessage', verbose_name='Письмо для рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.BooleanField(default=False, verbose_name='Ежедневно')),
                ('weekly', models.BooleanField(default=False, verbose_name='Еженедельно')),
                ('monthly', models.BooleanField(default=False, verbose_name='Ежемесячно')),
            ],
            options={
                'verbose_name': 'Периодичность',
                'verbose_name_plural': 'Периодичности',
            },
        ),
        migrations.CreateModel(
            name='MailingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.BooleanField(blank=True, default=True, null=True, verbose_name='Рассылка создана')),
                ('is_started', models.BooleanField(blank=True, default=False, null=True, verbose_name='Рассылка запущена')),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Рассылка завершена')),
            ],
            options={
                'verbose_name': 'Статус рассылки',
                'verbose_name_plural': 'Статусы рассылки',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус отправки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('mailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mailer', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_date', models.DateField(verbose_name='Дата начала рассылки')),
                ('mailing_time', models.TimeField(verbose_name='Время для рассылки')),
                ('mailing_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailingperiod', verbose_name='Периодичность рассылки')),
                ('mailing_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailingstatus', verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Настройки рассылки',
                'verbose_name_plural': 'Настройки рассылок',
            },
        ),
        migrations.AddField(
            model_name='mailer',
            name='mailing_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailingsettings', verbose_name='Настройки рассылки'),
        ),
    ]
